import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';

class ExportHelper {
  static Future<String> generateAndShareCSV({
    required List<Map<String, dynamic>> transactions,
    required String fileName,
    required String title,
  }) async {
    try {
      final directory = await getApplicationDocumentsDirectory();
      final filePath = '${directory.path}/$fileName.csv';
      final file = File(filePath);

      final buffer = StringBuffer();
      buffer.writeln(title);
      buffer.writeln('Generated: ${DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())}');
      buffer.writeln('');
      buffer.writeln('Date,Type,Description,Amount,Payment Method');

      for (final t in transactions) {
        buffer.writeln(
          '${DateFormat('yyyy-MM-dd HH:mm').format(t['date'])},'
          '${t['type']},'
          '"${t['description']}",'
          '${t['amount']},'
          '${t['paymentMethod'] ?? ""}',
        );
      }

      await file.writeAsString(buffer.toString());

      await Share.shareXFiles(
        [XFile(filePath)],
        subject: title,
        text: 'Exportou from Billing App',
      );

      return filePath;
    } catch (e) {
      print('CSV Export Error: $e');
      rethrow;
    }
  }

  static Future<String> generateAndSharePDF({
    required Map<String, dynamic> reportData,
    required String fileName,
    required String title,
  }) async {
    try {
      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (context) => [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    title,
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.Text(
                    DateFormat('dd/MM/yyyy').format(DateTime.now()),
                    style: const pw.TextStyle(fontSize: 12),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            _buildSummarySection(reportData),
            pw.SizedBox(height: 20),
            if (reportData.containsKey('ivaDetails'))
              _buildIVASection(reportData['ivaDetails']),
            pw.SizedBox(height: 20),
            _buildTransactionsTable(reportData['transactions'] ?? []),
            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.Text(
              'Generated by Billing App - Angola',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
            ),
          ],
        ),
      );

      final directory = await getApplicationDocumentsDirectory();
      final filePath = '${directory.path}/$fileName.pdf';
      final file = File(filePath);

      await file.writeAsBytes(await pdf.save());

      await Share.shareXFiles(
        [XFile(filePath)],
        subject: title,
        text: 'Exportou from Billing App',
      );

      return filePath;
    } catch (e) {
      print('PDF Export Error: $e');
      rethrow;
    }
  }

  static pw.Widget _buildSummarySection(Map<String, dynamic> data) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Summary',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 12),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _buildSummaryItem('Total Sales', data['totalSales'] ?? 0),
              _buildSummaryItem('Total Expenses', data['totalExpenses'] ?? 0),
              _buildSummaryItem('Net Profit', data['netProfit'] ?? 0),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSummaryItem(String label, double amount) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label, style: const pw.TextStyle(fontSize: 10)),
        pw.Text(
          'Kz ${NumberFormat('#,##0.00').format(amount)}',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }

  static pw.Widget _buildIVASection(Map<String, dynamic> ivaData) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.blue),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'IVA (14%) Report for AGT',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 12),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('IVA Arrecadado:'),
              pw.Text('Kz ${NumberFormat('#,##0.00').format(ivaData['ivaCollected'] ?? 0)}'),
            ],
          ),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('IVA Pago:'),
              pw.Text('Kz ${NumberFormat('#,##0.00').format(ivaData['ivaPaid'] ?? 0)}'),
            ],
          ),
          pw.Divider(),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('IVA Líquido:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(
                'Kz ${NumberFormat('#,##0.00').format(ivaData['ivaNet'] ?? 0)}',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildTransactionsTable(List transactions) {
    if (transactions.isEmpty) {
      return pw.Text('Sem transações');
    }

    return pw.TableHelper.fromTextArray(
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
      cellPadding: const pw.EdgeInsets.all(4),
      headers: ['Date', 'Type', 'Description', 'Amount'],
      data: transactions.map((t) => [
        DateFormat('dd/MM').format(t['date']),
        t['type'],
        (t['description'] as String).substring(0, (t['description'] as String).length > 20 ? 20 : (t['description'] as String).length),
        'Kz ${NumberFormat('#,##0').format(t['amount'])}',
      ]).toList(),
    );
  }

  static Future<String> createAGTReport({
    required Map<String, dynamic> data,
    required String period,
  }) async {
    return generateAndSharePDF(
      reportData: data,
      fileName: 'AGT_Report_${DateTime.now().millisecondsSinceEpoch}',
      title: 'AGT Tax Report - $period',
    );
  }

  static Future<String> createCSVExport({
    required List<Map<String, dynamic>> transactions,
    required String type,
  }) async {
    return generateAndShareCSV(
      transactions: transactions,
      fileName: '${type}_Export_${DateTime.now().millisecondsSinceEpoch}',
      title: '$type Export',
    );
  }
}